### ISSUE TITLE
Unable to use HTTP in v1.9.0

### ISSUE THREAD

**Issue by daliboris** [eXist-db/xst#163] opened 2023-10-21 23:25 UTC
### What happened?

Setting properties  `"secure" : false, "protocol": "http:"` in config file raises an error:

```text
Parse Error: Expected HTTP/
```

A different combination of properteis (`"secure" : false, protocol": "https:"`) will raise a diffeent error:

```text
Protocol "https:" not supported. Expected "http:"
```

If use  only `"protocol": "http:"` (withou `secure` property) following error occurs:

```text
Protocol "http:" not supported. Expected "https:"
```

### System Information

```sh
Running xst info --config redaktor.xstrc raises the same errors. Without configuration:

Build: eXist-6.2.0 (c8fa4958b6d4a50bd0cba7f3e76a150226414187)
Java: 11.0.16.1 (Microsoft)
OS: Windows 10 10.0 (amd64)
```

**Comment by line-o** [comment] 2023-10-21 23:28
Remove the secure option. The protocol is enough. I tried to make that point clear in the readme.
But it should fail with an actionable error.

**Comment by line-o** [comment] 2023-10-21 23:30
It's either the deprecated option "secure" _or_ "protocol"

**Comment by daliboris** [comment] 2023-10-21 23:32
Using only `"protocol": "http:"` value different error will occur: `Protocol "http:" not supported. Expected "https:"`

I don't have HTTPS on my laptop.

**Comment by line-o** [comment] 2023-10-22 08:04
Did you set the correct port to use, because the default is 8443?
```
{
  "connectionOptions": {
    "basic_auth": {
        "user": "admin",
        "pass": ""
    },
    "protocol": "http:",
    "host": "localhost",
    "port": 8080
  }
}
```

**Comment by line-o** [comment] 2023-10-22 09:04
The error indicates that you have a standard exist-db setup listening on _both_ 8080 ('http:') _and_ 8443 ('https:').

**Comment by line-o** [comment] 2023-10-22 09:06
@daliboris what happens if you only set
```json
{
  "connectionOptions": {
    "basic_auth": {
        "user": "admin",
        "pass": ""
    }
}
```

**Comment by line-o** [comment] 2023-10-22 09:11
Re-reading your issue I am confident that you are really only missing to set the port to `8080`. If that works for you I will close the issue.

**Comment by line-o** [comment] 2023-10-24 10:33
It turns out that v1.9.0 was used and the issue is fixed with https://github.com/eXist-db/xst/commit/cf75c70844d839342e20030b540cc4ef40c5316a

**Closed by line-o** 2023-10-24 10:33 UTC
Labels: bug, documentation
